SELECT USERNAME, COUNT(P.POST_ID) AS 'count loaded posts'
FROM USER AS U 
JOIN POST P ON U.USER_ID = P.USER_ID 
WHERE P.CREATED_AT >= CURRENT_DATE() - 10
GROUP BY U.USER_ID 
HAVING COUNT(P.POST_ID) > 3;