USE usersdb;

SELECT USERNAME, COUNT(P.POST_ID) 'number of posts loaded today' 
FROM USER AS U JOIN POST P ON U.USER_ID = P.USER_ID 
WHERE P.CREATED_AT = CURDATE()
GROUP BY U.USER_ID 
HAVING COUNT(P.POST_ID) > 3;